student_file: content/my_profile.yaml

projects:
  - content/projects/aws.yaml
  - content/projects/dynamics.yaml
  - content/projects/tiktok.yaml

theme: editorial-dark

site_title: "Lowell Monis | Data Scientist for Social Impact"
